### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by skyfrk** [dante-ev/docker-texlive#13]
https://github.com/dante-ev/docker-texlive/runs/769502469?check_suite_focus=true#step:4:2232

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 inkscape : Depends: libgomp1 (>= 4.9) but it is not going to be installed
            Depends: libmagick++-6.q16-8 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I guess `/etc/apt/sources.list` has to be updated?

https://github.com/dante-ev/docker-texlive/blob/master/Dockerfile#L18

**Comment by koppor** [comment]
I am trying to get this image stable somehow. When going to debian unstable completely, texlive breaks by now and then. Still thinking of how to solve that. See https://github.com/dante-ev/docker-texlive/issues/9 for a discussion.

Contributions welcome!

We can also have a private chat. Just drop me an email (you find it on my GitHub profile).

**Comment by skyfrk** [comment]
Thank you!
