### ISSUE TITLE
consider including bibtool?

### ISSUE THREAD

**Issue by pazz** [dante-ev/docker-texlive#16]
I'd like to call [bibtool](https://github.com/ge-ne/bibtool) inside my build scripts to generate a clean bibliography file before compiling.
Now, it seems that this is not part of texlive (I thought it was), so it requires an extra installation.
On Debian, `apt install bibtool` does the trick, but although this docker image is based on debian, this command seems to fail:

.gitlab-ci.yml:

```
default:
  image: danteev/texlive
  before_script:
    - apt install bibtool

build:
  script:
    - cd src
    - bibtool -r bib/bibtoolrc content/references.bib > content/references-clean.bib                         
    - latexmk -f -outdir=.. -pdf main.tex
  artifacts:
    paths:
      - "main.pdf"
```

log:
```
Skipping Git submodules setup
$ apt install bibtool

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package bibtool
ERROR: Job failed: exit code 1
```

**Comment by splitt3r** [comment]
You should do sth. like https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#sort-multi-line-arguments. And also build your own custom Docker image based on this one. Otherwise it will install the package every time your Pipeline runs.

**Comment by pazz** [comment]
Sure, I could do that, but the main attraction of this project for me is that it maintains a complete texlive image that I can simply use in my CI tasks. I solved this particular case simply by checking in the outputs of bibtools..

**Comment by splitt3r** [comment]
Yeah you are right on that point :). But adding every tool from the enourmus TeX world would make this image even bigger. So the extension via an own Docker file is very straight forward way. And GitLab and GitHub have build in Registries thus it is even faster then pulling the image from Docker Hub. Which has rate limits now.

**Comment by pazz** [comment]
Alright then, I will close the issue. Thanks for the pointer about build registries. I will have a look at this.
Happy new year :)

**Comment by koppor** [comment]
Nice discussion. I think, this image should be a ready-to-go image for most use cases. Therefore, a JRE is included and some other tools. Making the image very large. This is sort of documented in [ADR-001](https://github.com/dante-ev/docker-texlive/blob/master/docs/adr/0001-do-not-base-on-any-tex-image.md) and [ADR-002](https://github.com/dante-ev/docker-texlive/blob/master/docs/adr/0002-provide-all-packages.md). Need to write it down better.

Customized images should IMHO base on https://github.com/reitzig/texlive-docker. Alternatively, we should work on flavours for ourselves. Maybe, we could also write a `Dockerfile` generator generating the right commands based on the `.tex` source code to compile.

Regarding [bibtool](https://github.com/ge-ne/bibtool), I am a bit biased as I am the core developer of [JabRef](http://www.jabref.org/), which can also be used on the command line. I know that its startup time is slower.

The reason why the installation fails is that there is no information available on packakges any more in the image: https://github.com/dante-ev/docker-texlive/blob/8488ace545d96290293980c7df8f795516fb5f3a/Dockerfile#L94

I think, bibtool is a small tool. Thus, the image size should not be significantly increased. Thus, I am trying to add it at https://github.com/dante-ev/docker-texlive/pull/17.

The hint on the other registries was given at https://github.com/dante-ev/docker-texlive/issues/10#issuecomment-753590874. Hopefully, I'll find the time to do so.
