### ISSUE TITLE
Pygments

### ISSUE THREAD

**Issue by kalaider** [dante-ev/docker-texlive#22]
[`Minted`](https://www.ctan.org/pkg/minted) requires [Pygments](https://pygments.org/) for syntax highlighting. Could you consider including it? The package should not noticeably increase the image size but would be very helpful as it allows the image to be use in more contexts out of the box.

**Comment by kalaider** [comment]
Looks like it is already in there, sorry. I found it out when I tried to build my custom image with pygments. Could you add pygments to README then?

**Comment by koppor** [comment]
Yeah, the [scientific thesis template](https://github.com/latextemplates/scientific-thesis-template) uses this image successfully. I have totally forgotten about the dependencies. At first sight, something different is installed in this image: https://github.com/dante-ev/docker-texlive/blob/23bb78d78c57026e0a05fcdb8703f566deb6f913/Dockerfile#L107

Will need to think about it. Maybe, mentioning that "minted" works, could also be an option?

Maybe, the support is also in the "upstream" Docker image: https://gitlab.com/islandoftex/images/texlive#tex-live-docker-image

**Comment by koppor** [comment]
Note that with lualatex, the new package [codehigh](https://ctan.org/pkg/codehigh) could be a good replacement:

> It is more powerful than the listings package, and more easy to use than minted.

**Comment by koppor** [comment]
I added https://github.com/dante-ev/docker-texlive/blob/main/test/minimal-minted.tex to check the build (via #31).

**Comment by koppor** [comment]
[MWE](https://tex.meta.stackexchange.com/a/3225/9075) for codehigh added at https://github.com/dante-ev/docker-texlive/pull/32.
