### ISSUE TITLE
Access to files in parent directories

### ISSUE THREAD

**Issue by dbitouze** [dante-ev/docker-texlive#39]
Suppose the following structure:
```
parent-directory
├── current-directory
│   └── current-file.tex % Contains: \documentclass{article}\begin{document}\input{../parent-file}\end{document}
└── parent-file.tex      % Contains: Hey, I'm the content of the parent file!
```
With a non Docker installation of the TeX Live and  a `texmf.cnf` file that contains `openout_any = r`, the compilation of `current-file.tex` is possible.

With the `docker` image you provide, all my attempts failed. So far I tried by adding a local `texmf.cnf` file containing `openout_any = r` in each of these directories and running:
```
$ cd /home/bitouze/parent-directory/current-directory
$ docker run --rm -it -v $(pwd):/workdir danteev/texlive pdflatex current-file
```
or:
```
$ cd /home/bitouze/parent-directory/current-directory
$ docker run --rm -it -v $(pwd)/..:/workdir danteev/texlive pdflatex current-directory/current-file
```
but in each case, that returns:

>! LaTeX Error: File `../parent-file.tex' not found.

With the `docker` image you provide, is it possible to compile files which input files in parent directories?

**Comment by koppor** [comment]
Thank you for the question.

The last one is a good start, because the `parent-file.tex` will be visible to docker.

> `docker run --rm -it -v $(pwd)/..:/workdir danteev/texlive pdflatex current-directory/current-file`

If you ran 

> `docker run --rm -it -v $(pwd)/..:/workdir danteev/texlive bash`

and then 

    ls -la

You would see `parent-file.tex` instead of `current-file.tex`.

pdflatex also resolves the directories relative to the current directory and not to the `.tex` one (does it?)

I fixed it as follows:

    docker run --rm -it -v $(pwd)/..:/workdir danteev/texlive /bin/bash -c "cd subdir1 && pdflatex current-file"
