### ISSUE TITLE
Texdoc doesn't work

### ISSUE THREAD

**Issue by Samuel-Martineau** [dante-ev/docker-texlive#46]
The image doesn't seem to contain documentation for any of the installed packages, even for `texdoc` itself.
**Examples:**
```
root@8ae96bb31d97:/workspaces/rapport# texdoc texdoc
Sorry, no documentation found for "texdoc".
If you are unsure about the name, try full-text searching on CTAN.
Search form: <https://www.ctan.org/search/>
```
```
root@8ae96bb31d97:/workspaces/rapport# texdoc csquotes
Sorry, no documentation found for "csquotes".
If you are unsure about the name, try full-text searching on CTAN.
Search form: <https://www.ctan.org/search/>
```
```
root@8ae96bb31d97:/workspaces/rapport# texdoc babel
Sorry, no documentation found for "babel".
If you are unsure about the name, try full-text searching on CTAN.
Search form: <https://www.ctan.org/search/>
```
In fact, I can't find a single package known to `texdoc`. Am I doing something wrong? Is this normal behaviour? If so, do you have any clues for how I could fix it?

**Comment by koppor** [comment]
It's not a bug, it's a feature. We aimed to reduce the image size.

The upstream image supports the build parameter `DOCFILES`. https://gitlab.com/islandoftex/images/texlive/-/blob/master/Dockerfile.latest#L5. See https://gitlab.com/islandoftex/images/texlive/-/tree/master#flavors-we-provide for some documentation around that. - Maybe, that image is sufficient for you?

Implementation note: This is implemented at https://github.com/dante-ev/docker-texlive/blob/0f4f495f313feb0c2c5d211670a8fd292f0b14cc/Dockerfile#L76.

**Comment by Samuel-Martineau** [comment]
Thank you
