### ISSUE TITLE
Automatic Builds for latest

### ISSUE THREAD

**Issue by kmindi** [dante-ev/docker-texlive#49]
The latest tag could benefit from automatic builds to be up-to-date

**Comment by koppor** [comment]
Please refine your request. There is an automatic check of the latest tag in place https://github.com/dante-ev/docker-texlive/blob/main/.github/workflows/check-build.yml. What do you miss there?

**Comment by kmindi** [comment]
I see that there is a schedule to build every two weeks. ("At 03:01 on day-of-month 1 and 15.")
I wasn't specific on how often there should be a rebuild. So that schedule fulfills building regularly automatically, thanks.

What I meant at the time of writing (IIRC) with "automatic build" was that there is a possibility to trigger the image build automatically, on docker hub, in the event that the underlying base image was (re-)build, e.g. in case of security patches.
But also fine like this if you don't see the need to be faster up-to-date with your image for cases like security.

**Comment by koppor** [comment]
> What I meant at the time of writing (IIRC) with "automatic build" was that there is a possibility to trigger the image build automatically, on docker hub, in the event that the underlying base image was (re-)build, e.g. in case of security patches.

The only use case I see for a quicker build is the integration of new LaTeX packages. A workaround for that is that a user manually adds them to their images.

> But also fine like this if you don't see the need to be faster up-to-date with your image for cases like security.

I did not make a thorough security analysis. Maybe it's a research topic to investigate the attack vectors and possible gains on LaTeX users. I would assume they know about the risks of Cloud computing, docker etc and surely have separate hardware for these tasks than their critical tasks. Also not using a laptop with an LED. https://blog.fefe.de/?ts=9a7678ed

Interesting times. 

I'll close the issue. If anyone wants to contribute to this with code, we can investigate further.
