### ISSUE TITLE
Debian stretch got archived by Debian

### ISSUE THREAD

**Issue by VynceCook** [dante-ev/docker-texlive#50]
The debian image used by docker-texlive is no longer maintained and has been archived. As a result, adding a packet to the container is no longer possible. An "apt-get update" performed in the container fails. Is an update of the debian image used planned?

**Comment by koppor** [comment]
I fixed it. You can use `2023-A` or `edge` (always latest build) as tag.

See https://github.com/dante-ev/docker-texlive/blob/main/CHANGELOG.md#changelog
