### ISSUE TITLE
plantuml.jar is overwritten if a docker volume is mounted on /home

### ISSUE THREAD

**Issue by skyfrk** [dante-ev/docker-texlive#6]
The `plantuml.jar` is overwritten if a docker volume is mounted on `/home`. If you then try to compile a document which uses the [plantuml](https://github.com/koppor/plantuml) CTAN package `plantuml.jar` is not available.

A quick workaround:  `docker run --rm -it -v /path/to/project:/home/work danteev/texlive bash -c 'cd work && latexmk -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape -pdf -pdflatex=lualatex document.tex'`

To fix this issue I'd suggest to either mount the `plantuml.jar` in another place or add a note to the readme.

**Comment by koppor** [comment]
I totally overlooked that thing. `/home` is now used for plantuml - and the build dir is now `/workdir`.

See https://github.com/dante-ev/docker-texlive/commit/f997b25822904726f33fc0025c604c170f401433#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 for the diff.
