### ISSUE TITLE
tlmgr does NOT update any package during build

### ISSUE THREAD

**Issue by rzippo** [dante-ev/docker-texlive#9]
In the Dockerfile, `texlive-full` in installed and later updated with `tlmgr update --all`.
However, when the latter is issued no package is updated, as `tlmgr` will see no packages as installed.

```
PS C:\> docker run -it danteev/texlive:latest                                                                           root@5fd1f6d862d6:/home# tlmgr info --only-installed
(running on Debian, switching to user mode!)
root@5fd1f6d862d6:/home# tlmgr update --all
(running on Debian, switching to user mode!)
tlmgr: package repository http://mirrors.ibiblio.org/pub/mirrors/CTAN/systems/texlive/tlnet (verified)
tlmgr: no updates available
```

Thus, the resulting packages will always be those included in the `texlive-full` Debian package, many of which are currently outdated.

**Comment by koppor** [comment]
Feel free to provide a fix using a PR.

**Comment by rzippo** [comment]
As I understand, this issue with `tlmgr` installed via `apt` is by design, as you are supposed to choose between the two distribution/update methods.

Thus the fix would be to install via [`install-tl`](https://www.tug.org/texlive/quickinstall.html) script insted of `apt`, which makes builds last an hour - I am not sure how feasible it would be to run them as frequently as you do.

I have modified the Dockerfile [here](https://github.com/rzippo/texlive) and uploaded a new docker image [here](https://hub.docker.com/repository/docker/rzippo/texlive).

**Comment by koppor** [comment]
Thank you for sharing!

I thought, there could be some hacks:

A) Convince tlmgr to update nevertheless
B) Use `apt-pin` to have tex packages from Debian did

Maybe, it's worth to sneak into https://github.com/reitzig/texlive-docker/blob/master/README.md. - I like full latex installations as users can focus on their document. Maybe, a "good" `Texlivefile` would be a solution. The last years, that was too hard for me...

Maybe, we can speed up local pulls by publishing a "base" image each month and a daily build basing on that image each day. That way, the build time and pull time will decrease. The cost is more space on the users side, which is IMHO acceptable.

**Comment by rzippo** [comment]
>  I like full latex installations as users can focus on their document

I absolutely agree, that is why I used this docker image in the first place. It contains additional software that packages may use, like inkscape.

> I thought, there could be some hacks:
> 
> A) Convince tlmgr to update nevertheless
> B) Use apt-pin to have tex packages from Debian did

I am not sure trying to get Debian packages to work like a manual installation is a proper solution. As I understand, that `tlmgr` is modified to be always in `--usermode`, so all it does is local to the user and does not modify what `apt` installed.

> Maybe, we can speed up local pulls by publishing a "base" image each month and a daily build basing on that image each day. That way, the build time and pull time will decrease. The cost is more space on the users side, which is IMHO acceptable.

This is far more doable, in my opinion. The daily build would just pick up from the base image and run `tlmgr update --all` and `apt update && apt upgrade -y`.

> Maybe, it's worth to sneak into https://github.com/reitzig/texlive-docker/blob/master/README.md

From what I understand, that requires manual configuration to decide which packages to include. Images are smaller, but then you have to manage what you need. As an example, my workflow is based in [this extension](https://github.com/James-Yu/LaTeX-Workshop) where I just put `danteex/texlive` in the settings and let it build automatically while I edit. I far prefer a no-thoughts image. 
Something that could be taken however is the version selection (20xx) to make complete images of past frozen distributions. 

The question now is whether the current solution, which uses Debian's pre-built packages, is preferable in some use cases and thus it would be better to maintain both this and my solution.

**Comment by koppor** [comment]
We switched to [island of tex's base image](https://gitlab.com/islandoftex/images/texlive), which does a weekly build using most recent texlive. Thus, no need to update any more.
